# Generated by Django 5.2.15 on 2026-06-16 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riskscore',
            name='risk_level',
            field=models.CharField(default='LOW', max_length=20),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN', 'LOGIN'), ('TRANSACTION', 'TRANSACTION'), ('PASSWORD_CHANGE', 'PASSWORD_CHANGE'), ('PROFILE_UPDATE', 'PROFILE_UPDATE')], max_length=50)),
                ('description', models.TextField()),
                ('risk_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
